import time
import os
import pathlib


from pdfminer.high_level import extract_pages
from pdfminer.image import ImageWriter
from pdfminer.layout import LTTextContainer, LTPage, LTTextBoxHorizontal, LTImage, LTFigure

from aidapta.utils import extract_mods_metadata
from aidapta.captions import find_caption_by_text, find_caption_by_bbox
from aidapta.image import sort_layout_elements, create_output_dir
from aidapta.metadata import Document, Metadata, Visual

# SELECT MODS FILE
MODS_FILE = "data-pipelines/data/4Manuel_MODS.xml"
# SELECT PDF FILE
# PDF_FILE = "data-pipelines/data/caption-tests/multi-image-caption.pdf"
# PDF_FILE = "data-pipelines/data/TheRevivaloftheJustCity-11pages.pdf"
PDF_FILE = "data-pipelines/data/TheRevivaloftheJustCity-pages-131.pdf"

# SELECT OUTPUT DIRECTORY
OUTPUT_DIR ="data-pipelines/img/pdfminer/"

# SETTINGS FOR THE IMAGE EXTRACTION
IMG_SETTINGS = {"width": 100, "height": 100}

# CAPTION MATCH SETTINGS
CAP_SETTINGS ={"method": "bbox",
           "offset": 10,
           "direction": "down"
           }


# EXTRACT METADATA FROM MODS FILE
meta_blob = extract_mods_metadata(MODS_FILE)

# create document object
pdf_document = Document(PDF_FILE)
# initialize metadata object
entry = Metadata(pdf_document)
# add metadata from MODS file
entry.set_metadata(meta_blob)

# PREPARE OUTPUT DIRECTORY
pdf_file_name = pathlib.Path(PDF_FILE).stem
image_directory = create_output_dir(OUTPUT_DIR, pdf_file_name)

# PROCESS PDF FILE
pdf_pages = extract_pages(PDF_FILE)

pages = []
for page in pdf_pages:
    elements = sort_layout_elements(page, img_height=IMG_SETTINGS["width"], img_width=IMG_SETTINGS["height"])
    pages.append(elements)

print("total pages", len(pages))

for page in pages:

    iw = ImageWriter(image_directory)
    print(f'images in page {page["page_number"]}, {len(page["images"])}')
    for img in page["images"]:
       
        visual = Visual(document_page=page["page_number"], document=pdf_document, bbox=img.bbox)
        
        for _text in page["texts"]:
            match = find_caption_by_bbox(img, _text, offset=CAP_SETTINGS["offset"], direction=CAP_SETTINGS["direction"])
            if match:
                # the following is necessary to remove break line `\n` from captions
                # that spans multiple lines
                caption = ""
                for text_line in match:
                    caption += text_line.get_text().strip() 
                # add caption to visual metadata
                visual.set_caption(caption)

        # rename image name to include page number
        img.name = "page" + str(page["page_number"]) + "-" + img.name
        # save image to file
        image_file_name =iw.export_image(img) # returns image file name, 
        # which last part is automatically generated by pdfminer to guarantee uniqueness
        
        # set location of image
        visual.set_location(os.path.join(image_directory, image_file_name))

        # add visual to entry
        entry.add_visual(visual)

# SAVE METADATA TO JSON FILE
entry.save_to_json(os.path.join(image_directory,"metadata.json"))










