"""A pipeline for extracting metadata from MODS files and imges from PDF files.
Author: Manuel Garcia
"""

import os
import pathlib
import shutil

from pdfminer.high_level import extract_pages
from pdfminer.image import ImageWriter
import time
from tqdm import tqdm
from aidapta.utils import extract_mods_metadata, get_entry_number_from_mods
from aidapta.captions import find_caption_by_bbox
from aidapta.image import sort_layout_elements, create_output_dir
from aidapta.metadata import Document, Metadata, Visual

start_time = time.time()

# SELECT MODS FILE
MODS_FILE = "data-pipelines/data/actual-data/00001_mods.xml"

# SELECT INPUT DIRECTORY
INPUT_DIR = "data-pipelines/data/actual-data/"

# SELECT OUTPUT DIRECTORY
# if run multiple times to the same output directory, the images will be duplicated and 
# metadata will be overwritten
OUTPUT_DIR ="data-pipelines/data/actual-data/"

# SETTINGS FOR THE IMAGE EXTRACTION
IMG_SETTINGS = {"width": 0, "height": 0} # recommended values: 0, 0

# CAPTION MATCH SETTINGS
CAP_SETTINGS ={"method": "bbox",
           "offset": 10,
           "direction": "down"
           }

# EXTRACT METADATA FROM MODS FILE
meta_blob = extract_mods_metadata(MODS_FILE)

# get entry number from MODS file
entry_number = get_entry_number_from_mods(MODS_FILE)

# Create output directory for the entry
entry_directory = create_output_dir(OUTPUT_DIR, entry_number)

# FIND PDF FILES FOR A GIVEN ENTRY
PDF_FILES = []
for f in tqdm(os.listdir(INPUT_DIR), desc="Searching PDF files", unit="files"):
    if f.startswith(entry_number) and f.endswith(".pdf"):
        PDF_FILES.append(INPUT_DIR+f)

# INITIALIZE METADATA OBJECT
entry = Metadata()
# add metadata from MODS file
entry.set_metadata(meta_blob)
# set web url. This is not part of the MODS file
web_url = "http://resolver.tudelft.nl/" + entry.uuid
entry.add_web_url(web_url)

# PROCESS PDF FILES
for pdf in PDF_FILES:
    print("--> Processing file:", pdf)
    # create document object
    pdf_document = Document(pdf)
    entry.add_document(pdf_document)

    # PREPARE OUTPUT DIRECTORY
    pdf_file_name = pathlib.Path(pdf_document.location).stem
    image_directory = create_output_dir(entry_directory, pdf_file_name)

    # PROCESS SINGLE PDF 
    pdf_pages = extract_pages(pdf_document.location)

    pages = []
    for page in tqdm(pdf_pages, desc="Processing pages", unit="pages"):
        elements = sort_layout_elements(page, img_height=IMG_SETTINGS["width"], img_width=IMG_SETTINGS["height"])
        pages.append(elements)

    for page in tqdm(pages, desc="Extracting images", total=len(pages), unit="pages"):

        iw = ImageWriter(image_directory)
       
        for img in page["images"]:
        
            visual = Visual(document_page=page["page_number"], document=pdf_document, bbox=img.bbox)
            
            for _text in page["texts"]:
                # caption matching by bbox use the first match. This might be an issue 
                # for images that overlap many text boxes
                match = find_caption_by_bbox(img, _text, offset=CAP_SETTINGS["offset"], 
                                            direction=CAP_SETTINGS["direction"])
                if match:
                    # the following is necessary to remove break line `\n` from captions
                    # that spans multiple lines
                    caption = ""
                    for text_line in match:
                        caption += text_line.get_text().strip() 
                    # add caption to visual metadata
                    visual.set_caption(caption)

            # rename image name to include page number
            img.name = "page" + str(page["page_number"]) + "-" + img.name
            # save image to file
            image_file_name =iw.export_image(img) # returns image file name, 
            # which last part is automatically generated by pdfminer to guarantee uniqueness
            
            # set location of image
            visual.set_location(os.path.join(image_directory, image_file_name))

            # add visual to entry
            entry.add_visual(visual)

# ORGANIZE ENTRY FILES 
# for data management purposes, the files are organized in the following way:
# PDF and MODS files are copied to the entry_directory, 
# and images are saved to subdirectories in the entry direct, subdirectory name is the pdf file name
# e.g.: 00001/00001_mods.xml, 00001/00001.pdf, 00001/00001/page1-00001.png, 00001/00001/page2-00001.png

# Copy MODS file and PDF files to output directory
shutil.copy(MODS_FILE, entry_directory)
for pdf in PDF_FILES:
    shutil.copy(pdf, entry_directory)

end_time = time.time()
print("total time", end_time - start_time)

# SAVE METADATA TO JSON FILE
entry.save_to_json(os.path.join(entry_directory,"metadata.json"))
